// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Based on API contract: auth module

import api from './api';
import type {
  RegisterDto,
  LoginDto,
  RefreshTokenDto,
  LogoutDto,
  AuthResponse,
} from '@/types/api';
import { handleApiError } from '@/utils/api-error';

/**
 * POST /api/auth/register
 * Register a new user
 */
export async function register(data: RegisterDto): Promise<AuthResponse> {
  try {
    const response = await api.post<AuthResponse>('/api/auth/register', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/auth/login
 * Authenticate user and get access token
 */
export async function login(data: LoginDto): Promise<AuthResponse> {
  try {
    const response = await api.post<AuthResponse>('/api/auth/login', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/auth/refresh
 * Refresh access token using refresh token
 */
export async function refreshToken(data: RefreshTokenDto): Promise<AuthResponse> {
  try {
    const response = await api.post<AuthResponse>('/api/auth/refresh', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/auth/logout
 * Logout user and invalidate refresh token
 */
export async function logout(data: LogoutDto): Promise<void> {
  try {
    await api.post('/api/auth/logout', data);
  } catch (error) {
    handleApiError(error);
  }
}
