// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Based on API contract: automate module

import api from './api';
import type { AutomateExpensiveDto } from '@/types/api';
import { handleApiError } from '@/utils/api-error';

/**
 * POST /api/automate/expensive-automate
 * Automate expensive transaction
 */
export async function automateExpensive(data: AutomateExpensiveDto): Promise<void> {
  try {
    await api.post('/api/automate/expensive-automate', data);
  } catch (error) {
    handleApiError(error);
  }
}
