// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Based on API contract: installments module

import api from './api';
import type { Installment, CreateInstallmentDto } from '@/types/api';
import { handleApiError } from '@/utils/api-error';

/**
 * GET /api/installments
 * List all installments for the authenticated user
 */
export async function getAllInstallments(): Promise<Installment[]> {
  try {
    const response = await api.get<Installment[]>('/api/installments');
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * GET /api/installments/:id
 * Get a specific installment by ID
 */
export async function getInstallmentById(id: string): Promise<Installment> {
  try {
    const response = await api.get<Installment>(`/api/installments/${id}`);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/installments
 * Create a new installment plan
 */
export async function createInstallment(data: CreateInstallmentDto): Promise<Installment> {
  try {
    const response = await api.post<Installment>('/api/installments', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/installments/:id/cancel
 * Cancel an active installment plan
 */
export async function cancelInstallment(id: string): Promise<void> {
  try {
    await api.post(`/api/installments/${id}/cancel`);
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * DELETE /api/installments/:id
 * Delete an installment plan
 */
export async function deleteInstallment(id: string): Promise<void> {
  try {
    await api.delete(`/api/installments/${id}`);
  } catch (error) {
    handleApiError(error);
  }
}
