// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Based on API contract: subscriptions module

import api from './api';
import type {
  Subscription,
  CreateSubscriptionDto,
  UpdateSubscriptionDto,
  GetSubscriptionsQuery,
} from '@/types/api';
import { handleApiError } from '@/utils/api-error';

/**
 * GET /api/subscriptions
 * List all subscriptions for the authenticated user
 * @param query - Optional filter by isActive status
 */
export async function getAllSubscriptions(query?: GetSubscriptionsQuery): Promise<Subscription[]> {
  try {
    const response = await api.get<Subscription[]>('/api/subscriptions', { params: query });
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * GET /api/subscriptions/:id
 * Get a specific subscription by ID
 */
export async function getSubscriptionById(id: string): Promise<Subscription> {
  try {
    const response = await api.get<Subscription>(`/api/subscriptions/${id}`);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/subscriptions
 * Create a new subscription
 */
export async function createSubscription(data: CreateSubscriptionDto): Promise<Subscription> {
  try {
    const response = await api.post<Subscription>('/api/subscriptions', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * PUT /api/subscriptions/:id
 * Update an existing subscription
 */
export async function updateSubscription(id: string, data: UpdateSubscriptionDto): Promise<Subscription> {
  try {
    const response = await api.put<Subscription>(`/api/subscriptions/${id}`, data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * DELETE /api/subscriptions/:id
 * Delete a subscription
 */
export async function deleteSubscription(id: string): Promise<void> {
  try {
    await api.delete(`/api/subscriptions/${id}`);
  } catch (error) {
    handleApiError(error);
  }
}
