// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Based on API contract: transactions module

import api from './api';
import type {
  Transaction,
  CreateTransactionDto,
  UpdateTransactionDto,
  ListTransactionsQuery,
  TransactionSummaryQuery,
  PaginatedResponse,
  TransactionSummary,
} from '@/types/api';
import { handleApiError } from '@/utils/api-error';

/**
 * GET /api/transactions
 * List transactions with optional filters and pagination
 */
export async function getAllTransactions(query?: ListTransactionsQuery): Promise<PaginatedResponse<Transaction>> {
  try {
    const response = await api.get<PaginatedResponse<Transaction>>('/api/transactions', { params: query });
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * GET /api/transactions/summary
 * Get transaction summary for a date range
 */
export async function getTransactionSummary(query?: TransactionSummaryQuery): Promise<TransactionSummary> {
  try {
    const response = await api.get<TransactionSummary>('/api/transactions/summary', { params: query });
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * GET /api/transactions/:id
 * Get a specific transaction by ID
 */
export async function getTransactionById(id: string): Promise<Transaction> {
  try {
    const response = await api.get<Transaction>(`/api/transactions/${id}`);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * POST /api/transactions
 * Create a new transaction
 */
export async function createTransaction(data: CreateTransactionDto): Promise<Transaction> {
  try {
    const response = await api.post<Transaction>('/api/transactions', data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * PUT /api/transactions/:id
 * Update an existing transaction
 */
export async function updateTransaction(id: string, data: UpdateTransactionDto): Promise<Transaction> {
  try {
    const response = await api.put<Transaction>(`/api/transactions/${id}`, data);
    return response.data;
  } catch (error) {
    handleApiError(error);
  }
}

/**
 * DELETE /api/transactions/:id
 * Delete a transaction
 */
export async function deleteTransaction(id: string): Promise<void> {
  try {
    await api.delete(`/api/transactions/${id}`);
  } catch (error) {
    handleApiError(error);
  }
}
