// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z
// Source: .claude/output/api-contract.json

// ==================== AUTH MODULE ====================

export interface RegisterDto {
  email: string;
  name: string;
  password: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface RefreshTokenDto {
  refreshToken: string;
}

export interface LogoutDto {
  refreshToken: string;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: {
    id: string;
    email: string;
    name: string;
  };
}

// ==================== AUTOMATE MODULE ====================

export interface AutomateExpensiveDto {
  value: number;
  nameStore: string;
}

// ==================== INSTALLMENTS MODULE ====================

export interface Installment {
  id: string;
  userId: string;
  description: string;
  totalAmount: number;
  totalInstallments: number;
  startDate: string;
  category: number;
  status: 'active' | 'cancelled' | 'completed';
  createdAt: string;
  updatedAt: string;
}

export interface CreateInstallmentDto {
  description: string;
  totalAmount: number;
  totalInstallments: number;
  startDate: string; // YYYY-MM-DD
  category: number;
}

// ==================== SUBSCRIPTIONS MODULE ====================

export interface Subscription {
  id: string;
  userId: string;
  description: string;
  amount: number;
  billingDay: number;
  type: number;
  category: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateSubscriptionDto {
  description: string;
  amount: number;
  billingDay: number;
  type: number;
  category: number;
}

export interface UpdateSubscriptionDto {
  description?: string;
  amount?: number;
  billingDay?: number;
  type?: number;
  category?: number;
  isActive?: boolean;
}

export interface GetSubscriptionsQuery {
  isActive?: string;
}

// ==================== TRANSACTIONS MODULE ====================

export interface Transaction {
  id: string;
  userId: string;
  description: string;
  amount: number;
  type: number;
  date: string;
  notes?: string;
  category: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTransactionDto {
  description: string;
  amount: number;
  type: number;
  date: string;
  notes?: string;
  category: number;
}

export interface UpdateTransactionDto {
  description?: string;
  amount?: number;
  type?: number;
  date?: string;
  notes?: string;
  category?: number;
}

export interface ListTransactionsQuery {
  startDate?: string;
  endDate?: string;
  type?: number;
  category?: number;
  page?: number;
  limit?: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
}

export interface TransactionSummaryQuery {
  startDate?: string;
  endDate?: string;
}

export interface TransactionSummary {
  income: number;
  expense: number;
  balance: number;
  period: {
    startDate: string;
    endDate: string;
  };
}

export interface ApiSuccessResponse<T = unknown> {
  success: true;
  data: T;
}

export interface ApiErrorResponse {
  success: false;
  message: string;
  details?: unknown;
}
