// Auto-generated by frontend-agent - DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T20:30:00.000Z

export class ApiError extends Error {
  constructor(
    public statusCode: number,
    message: string,
    public details?: unknown
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export function handleApiError(error: unknown): never {
  if (error instanceof ApiError) {
    throw error;
  }

  // Handle axios errors
  if (typeof error === 'object' && error !== null && 'response' in error) {
    const axiosError = error as {
      response?: { status: number; data?: { message?: string } };
      message: string;
    };

    const status = axiosError.response?.status || 500;
    const message = axiosError.response?.data?.message || axiosError.message || 'Unexpected error';

    throw new ApiError(status, message, axiosError.response?.data);
  }

  // Generic error
  throw new ApiError(500, 'Unexpected error', error);
}
